### ISSUE TITLE
When enable this extension, the IntelliSense in VSCode will not support the anonymous structs or unions

### ISSUE THREAD

**Issue by ustbshen** [IARSystems/iar-vsc-build#1]
When I define a structure which contain an anonymous structs or unions, the IntelliSense will report error that [struct xxx has no field yyy.], but build result is success.
For example:
```
typedef struct test
{
  int a;
  int b;
  union _u
  {
    char c;
    short d;
    float e;
    double f;
  };
} test_t;

void test_func()
{
    test_t t1;
    t1.c = '\n';  //IntelliSense will report [struct "test" has no field "c"]
}
```
But if I disable the IAR build extension and use my own "c_cpp_properties.json", there is no error reported.

**Comment by HampusAdolfsson** [comment]
The extension sets the IntelliSense mode to clang-arm, and by default clang does not allow unnamed unions with tags:
```c
// allowed by IAR, not allowed by clang
struct test {
  union _u {
    char c;
  };
}
// allowed by both IAR and clang
struct test {
  union {
    char c;
  };
}
```
I can fix this by adding the `-fms-extensions` parameter to the IntelliSense. That should make the IntelliseSense behave the same as the IAR compiler.
