### ISSUE TITLE
In Compatibility table Version maybe mistake written to 7.10.

### ISSUE THREAD

**Issue by Femtometer** [IARSystems/iar-vsc-build#2]
> This extension is compatible with any IAR Embedded Workbench (EW) or IAR Build Tools version (BX) using IDE version 8 or newer. 

![image](https://user-images.githubusercontent.com/5461891/173779779-fdc47ae0-cdf2-427c-bb5c-0c89dd133e9f.png)

**Comment by micaelbo** [comment]
It should be "Arm v8.10-9.20.3". To be corrected in the next update.

**Comment by micaelbo** [comment]
Closes #2
