### ISSUE TITLE
IAR7.80 Can't use

### ISSUE THREAD

**Issue by xuejianqiang123** [IARSystems/iar-vsc-build#22]
iar: Rebuild Project 

> 'c:\IAR784/common/bin/iarbuild.exe' 'e:\TTC_TC_20200423_V3.3_Release\examples\rtos\CC2640R2_LAUNCHXL\sysbios\hello\tirtos\iar\hello.ewp' '-build' 'Debug' '-log' 'info' '-parallel' '4'

     IAR Command Line Build Utility V7.5.6.4719
     Copyright 2002-2017 IAR Systems AB.

Building configuration: hello - Debug
Updating build tree...

0  file(s) deleted.
Updating build tree...

Configuration is up-to-date.

**Comment by HampusAdolfsson** [comment]
Hi,

This extension does not support EWARM 7.80. It requires EWARM 8.10.1 or later.
