### ISSUE TITLE
Filter for build in terminal (warnings, remaks, errors)

### ISSUE THREAD

**Issue by TLorenzPH** [IARSystems/iar-vsc-build#26]
Should be possible like in IAR console
![image](https://user-images.githubusercontent.com/112183749/186922097-64ea04bc-4703-4688-ab8e-f1389267b878.png)

**Comment by HampusAdolfsson** [comment]
We can add an option for this. 

VS Code also has built-in filtering of issues in the Problems view, as an alternative to using the build log.

**Comment by HampusAdolfsson** [comment]
The latest release (1.20.1) adds a "Build output log level" setting.
