### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cesarjacko** [IARSystems/iar-vsc-build#3]
[iarsystems.iar-build-unresponsive.cpuprofile.txt](https://github.com/IARSystems/iar-vsc-build/files/8911893/iarsystems.iar-build-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `iar-build`
- Extension Version: `1.10.2`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/RAMIRE~1/AppData/Local/Temp/iarsystems.iar-build-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by HampusAdolfsson** [comment]
Thanks for the report! 
This was caused by some inefficient code for finding IAR toolchain installations. I have now optimized it, so you should see significantly faster activation times in the next release.
