### ISSUE TITLE
Duplicate Groups Created When Adding Files to Project

### ISSUE THREAD

**Issue by cookthebook** [IARSystems/iar-vsc-build#33]
I have been using the IAR VS Code extension since my project upgraded to IAR 9. I noticed that if I add a file to the project in VS Code, for any group at the same level as the new file, a new empty group with the same name also gets created.

![image](https://user-images.githubusercontent.com/7623377/210631706-9d709a99-a1e6-4b4d-826d-ef20e0d77b9f.png)
![image](https://user-images.githubusercontent.com/7623377/210632705-ac30ec26-5bde-4d16-8552-ddbbd3e6b628.png)

This happens regardless of the alphabetical order of the new file:

![image](https://user-images.githubusercontent.com/7623377/210632893-d0b9da4e-5aa7-4441-9a5e-0a5d0fee88b6.png)

I am using EWARM 9.20.4 and v1.20.1 of the IAR Build extension on Windows 10.

**Comment by cookthebook** [comment]
I was looking through the closed issues, and this might be a duplicate of https://github.com/IARSystems/iar-vsc-build/issues/12 ?

I can edit the project perfectly fine in the IAR Embedded Workbench, seems strange to me that there would be a disparity between the tools.

**Comment by HampusAdolfsson** [comment]
I've added a workaround for the bug, which will be included in the next release. It should fix all cases of duplicated groups.

Note that the bug also causes you to be unable to remove any groups or files from a project in VS Code. There's nothing we can do about it, but there's now an error message to explain *why* groups/files aren't being removed.

**Comment by cookthebook** [comment]
Thank you! I will watch for the next release.
