### ISSUE TITLE
gcc style __attribute__ not recongnized

### ISSUE THREAD

**Issue by HiFiPhile** [IARSystems/iar-vsc-build#34]
Hi,

For example this code report error:
```
__attribute__((always_inline))
void BSP_Init()
{
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
    RCC->APB1ENR |= RCC_APB1ENR_PWREN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOHEN;
    
}
```
![image](https://user-images.githubusercontent.com/4375114/212490891-ef486b31-c7a4-4ee5-b184-b448524cac7a.png)

**Comment by HampusAdolfsson** [comment]
We've received similar reports from others and are working on resolving this.

As a workaround, you can trick intellisense into ignoring the `__attribute__` declaration. To do so, go to the extension settings, and under `Defines`, add the following:
```
__attribute__(x)=
```
