### ISSUE TITLE
Support Attach to Running Target

### ISSUE THREAD

**Issue by gcampbell-msft** [IARSystems/iar-vsc-build#38]
There are lots of workflows where it is necessary to attach to a running target in order to debug hardware in it's current state. It can be difficult to use the Download cycle in order to try and get the board back into the state that I'm trying to debug.

**Comment by HampusAdolfsson** [comment]
Closing this in favor of [#15](https://github.com/IARSystems/iar-vsc-debug/issues/15) in the iar-vsc-debug repo.
