### ISSUE TITLE
Command to get path to the built executable

### ISSUE THREAD

**Issue by axel-lebourhis** [IARSystems/iar-vsc-build#39]
Hi,

CMake Tools extension provide a command to retrieve the path to the executable: ${command:cmake.launchTargetPath}
It would be great to have a similar feature for this IAR extension, as it helps to create generic launch configurations, shared among teams.

Thanks a lot !

**Comment by HampusAdolfsson** [comment]
Hi! What executable are you trying to find the path to? If it is an executable in the Embedded Workbench installation directory, we provide the `${command:iar-config.toolchain}` command which resolves to the selected Embedded Workbench or Build Tools installation.

For example:
`${command:iar-config.toolchain}/common/bin/iarbuild.exe` gives you the iarbuild executable, and `${command:iar-config.toolchain}/arm/bin/iccarm.exe` gives you the Arm compiler.

**Comment by axel-lebourhis** [comment]
Hi ! No, I meant the output executable from the build.
The idea is to have a command that returns the absolute path to the .out of the currently loaded ewp, this way we can have generic launch configuration shared among teams.

**Comment by HampusAdolfsson** [comment]
I see. For various reasons this is a bit complicated (but not impossible) to implement. If you haven't changed the output path from the default, you can get the path to the .out file like this:
`${command:iar-config.project-file}/../${command:iar-config.project-configuration}/Exe/${command:iar-config.project-name}.out`

Would that work for you?

**Comment by axel-lebourhis** [comment]
I tried your suggestion, it does the job for us ! Thanks for the tip.
