### ISSUE TITLE
IAR build in VSCode is slower than in IAR Workbench

### ISSUE THREAD

**Issue by LucaGotti** [iarsystems/iar-vsc-build#42]
It's at least two times longer !

**Comment by LucaGotti** [comment]
@jlonnberg 
Just to clarify, the -ninja option has to be added in vscode ? 
could u briefly guide us on how to do that ?

**Comment by jlonnberg** [comment]
There is not specific action for it, so you'll need to manually run "iarbuild [proj-name] -ninja [configuration]"  to generate the ninja file. You can also define it as a custom task, https://code.visualstudio.com/docs/editor/tasks#_custom-tasks, to make generation a bit easier. To build, simply navigate to the configuration directory and run "ninja"

**Comment by LucaGotti** [comment]
@jlonnberg : just as a reference, after having generated the ninja file, in vscode a complete rebuild takes roughly the same as workbench : both now takes about 6 minutes .
Many thanks for the useful hint !
