### ISSUE TITLE
Support for Linux and Mac user

### ISSUE THREAD

**Issue by whitescreens** [IARSystems/iar-vsc-build#46]
Hi,

Is there a way to make this extension working on Mac and Linux?
Silabs is able to do it with there IDE using Wine. See link below

https://community.silabs.com/s/article/MacOS-Support-for-Keil-8051-and-IAR-EW-Toolchains?language=en_US

Thanks for you help, and thank you for this amazing tool :) 

Alex

**Comment by jlonnberg** [comment]
@whitescreens The IAR toolchain is currently available for both linux and windows, whereas the linux support is only for the build tools. We don't offer any support for Mac at this point of time. See https://www.iar.com/bxarm for more information.
