### ISSUE TITLE
Support for .custom_argvars files.

### ISSUE THREAD

**Issue by nxj** [IARSystems/iar-vsc-build#5]
Last thing missing for me to be able to use this extension is support for .custom_argvars files. As a workaround i can just add the "-varfile C:\path\to\project.custom_argvars" to the extraBuildArguments in the workspace settings. But this only works with an absolute path and because variables are not allowed in the settings, it is not very portable. Would be great if some general support for these files could be added!

**Comment by HampusAdolfsson** [comment]
Until we implement proper support for this, would it help if we allowed build arguments to be relative to the workspace?
Then, if the open folder is `C:\path\to`, you could simply specify `"-varfile project.custom_argvars"` to mean `C:\path\to\project.custom_argvars`. It would be a simple change to make and would make the setting more portable.

**Comment by nxj** [comment]
That sounds great and would help!

**Comment by ycsin** [comment]
I wonder if this is in the 1.10.4 already?

![image](https://user-images.githubusercontent.com/1563974/179182095-448cfca0-b8a7-4a54-86e9-114004aebdba.png)

I'm getting this error

```
     IAR Command Line Build Utility V8.4.8.6680
     Copyright 2002-2020 IAR Systems AB.


 Usage:
 iarbuild <projectfile> [-clean | -build | -make | -cstat_analyze | -cstat_clean]
 <config> [-log errors|warnings|info|all] [-parallel <number>] [-varfile <argvarfile>]


 ERROR, Unknown command: "-varfile Project.custom_argvars" is not a valid command

WARN: Builder closed without reaching linking stage.
Source configuration did not complete: Process exited with code: 31
```

**Comment by ycsin** [comment]
Fixed, the arg needs to be on the next item instead of inline
![image](https://user-images.githubusercontent.com/1563974/179183378-5b98cc77-8b3e-4684-9ac6-d8b02c6ba9da.png)

**Comment by HampusAdolfsson** [comment]
Custom Argvars support has now been added, and you should no longer add extra build arguments for it. They are added automatically when you select a .custom_argvars file in the extension configuration view.
