### ISSUE TITLE
Impossible to deselect Custom Argument Variables File (.custom_argvars)

### ISSUE THREAD

**Issue by NotKasperNielsen** [IARSystems/iar-vsc-build#51]
I use a `.custom_argvars file` to inject build data from my CI system at compile time.
This file is generated before running `IarBuild.exe`

The VS Code plugin recognizes this file and selects that as the Custom Argument Variables File for the project.

Problem 1: 
There is no option to deselect a `.custom_argvars` file after one has been detected.
![image](https://github.com/IARSystems/iar-vsc-build/assets/88884973/b73d6baf-abe4-490a-a709-25a676930739)

Problem 2:
If the `.custom_argvars` is deleted, the VC Code plugin will still try to call `IarBuild.exe` with the old arg-file as input. This predictably fails.
Even though the UI shows: "No .custom_argvars file found"
![image](https://github.com/IARSystems/iar-vsc-build/assets/88884973/71342949-ce44-49a8-a315-7968e78afb6d)

If any of this happens I have to add a dummy `.custom_argvars` with no entries. Otherwise I can only compile using EW.

**Comment by HampusAdolfsson** [comment]
The support for `.custom_argvars` files is about to change in the new release of the extension. It will work just like in Embedded Workbench, where you select a `.eww` file and the extension automatically uses the `.custom_argvars` file with the same name, if one exists. Does this work for your use case?

Problem 2 will be fixed in this release. The `.custom_argvars` dropdown has been replaced with a `.eww` dropdown, but if you remove all `.eww` files you should no longer see `IarBuild.exe` using a deleted `.custom_argvars` file.

**Comment by NotKasperNielsen** [comment]
I actually really like that seeing and selecting which argfile is used is so easy right now.

Automatically selecting the argfile that matches the .eww as default is a logical step. But as I see it, that is almost already the case. If it selects the first (or any) of the files it finds, then if you only have one, it is automatically selected.

If this selection becomes automatic and hidden, like in Embedded Workbench, it just makes it more opaque what you are actually building. EW already doesn't tell you which file it is using.

In my CI system I specifically use a different argfile (ignored by git), so I can inject build variables at compile time without "dirtying" my repo status.
If I can't easily switch between argfiles, it makes my workflow more complicated.
Likewise, it would be very nice to easily tell VS Code to not use any argfile. Especially since right now my project is locked-up because it wants an argfile that no longer exist. It won't even allow me to clean the project. 
![image](https://github.com/IARSystems/iar-vsc-build/assets/88884973/6a123d85-87fb-40ca-bec4-90e8bd722236)

This despite actually creating and selecting a new `.custom_argvars` file.
![image](https://github.com/IARSystems/iar-vsc-build/assets/88884973/23521d60-cf7e-47c6-9c86-61ec21745a4f)

Do you have I indication of when this new release is expected to ship?


// Thanks

**Comment by HampusAdolfsson** [comment]
The release is expected to ship on monday.

Unfortunately there are some technical limitations that prevent us from keeping the `.custom_argvars` selector with the new `.eww` selector (and we need the `.eww` selector to enable features like batch builds).

For your use case, it sounds like it would be a good idea to configure the build task(s) manually in a `.vscode/tasks.json` file. The following is the default task for building:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "iar",
			"command": "build",
			"project": "${command:iar-config.project-file}",
			"config": "${command:iar-config.project-configuration}",
			"builder": "${command:iar-config.toolchain}/common/bin/iarbuild.exe",
			"label": "iar: Build Project",
			"argumentVariablesFile": "${command:iar-config.argument-variables-file}",
			"problemMatcher": [
				"$iar-cc",
				"$iar-linker"
			]
		}
	]
}

```

By default, the `argumentVariablesFile` field uses whatever you've selected in the UI, but you can change it to for example:
* Use a specific file, and have different build tasks for different `.custom_argvars` files.
* Use an [Input Variable](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables) to make VS Code ask you which `.custom_argvars` file to use each time.

**Comment by NotKasperNielsen** [comment]
OK, that makes sense.

I'll look into manually configuring tasks. Do you know if there is anywhere I can learn more about the IAR specific task config parameters?

Looking forward to Monday 😉

**Comment by HampusAdolfsson** [comment]
We don't have any extensive documentation for the tasks.json parameters, but you can use the intelliSense provided by VS Code to get short descriptions of each parameter. 

For most parameters, you can either use the command variables in the example above to use whatever is selected in the UI, or provide your own path to a specific file (e.g. a `.custom_argvars` for `argumentVariablesFile` or a `.ewp` for `project`).

**Comment by NotKasperNielsen** [comment]
Thanks.

**Comment by NotKasperNielsen** [comment]
I found one workaround for when IAR Build is stuck on a `.custom_argvars` file that no longer exists.
First: Delete this line in the `iar-vsc.json` file.
![image](https://github.com/IARSystems/iar-vsc-build/assets/88884973/8a32a17c-89cb-4de6-adaa-dae335ab0aec)


Then, importantly: Restart VS Code before doing anything else.
Apparently that actually forces IAR Build to look at the config file.
