### ISSUE TITLE
Error initiating IAR toolchain backend. Some functionality may be unavailable (Error: Service registry exited prematurely, code: 1).

### ISSUE THREAD

**Issue by fubinfeng2333** [IARSystems/iar-vsc-build#55]
I used the iar8.10.1 version to create the project before, and then I installed the iar9.40.1 version today to open the previous project, make it into the 9.40 version, and then use the iar build plug-in. At the beginning, it can still display the file structure, but then I don’t know why it doesn’t show it. Please take a look for me, thanks.
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/869902c7-5e1c-4bc0-9844-753380b21a34)
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/6e75899e-ff93-490f-bbe4-caec3fe9de88)
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/86c496e7-a0ec-4e58-a648-f7bb0d47b49e)

**Comment by jlonnberg** [comment]
Hi!
Can you try opening the project in EWARM once and save the project to ensure that it's been properly upgraded before trying it out in VSCode again?

BR
Joakim

**Comment by fubinfeng2333** [comment]
I made sure that I have converted the iar8.10 project to 9.40, please see the picture below, when I open the old project with the 9.40 version, it pops up these windows, and I have selected yes, even I have compiled the project.
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/6bc6d768-078c-42f5-b6cc-6f96b4e630f0)
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/3c57a330-7529-4652-895f-adba063d7a8a)

**Comment by jlonnberg** [comment]
Can you include the log from IAR Build for me when the problem occurs? It can be obtained from the output tab and select "IAR Build" in the dropdown menu.

Moreover, are you able to build the project properly usign the iarbuild build task? If so, can you please include the build output as well.

**Comment by fubinfeng2333** [comment]
The following screenshot is the log of IAR build:
![企业微信截图_16920779955913](https://github.com/IARSystems/iar-vsc-build/assets/34903713/8ba7bfd6-d06c-4dce-b205-434e487a772d)
![企业微信截图_16920780298601](https://github.com/IARSystems/iar-vsc-build/assets/34903713/91fbca0c-9c44-433a-92ce-89ca258432a6)

**Comment by jlonnberg** [comment]
Does the path to the project contain any non-ascii characters? Moreover, is it possbile for us to get the project to test internally?

**Comment by jlonnberg** [comment]
Please also consider if the suggested fix for #58 might fix this problem as well

**Comment by fubinfeng2333** [comment]
I updated iar build to v1.30.3, but found the same problem.
![1693552858222](https://github.com/IARSystems/iar-vsc-build/assets/34903713/91ab5be3-59aa-461b-b143-1fa3146e39a9)

**Comment by fubinfeng2333** [comment]
It seems that this problem will occur whenever the iar project is converted from version 8.0 to version 9.0 or above. I tried it with the project (EWARM V8) generated by stm32cube, and the result was the same.
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/49663e37-9962-48c7-b90e-7e8b8a5670b8)

**Comment by jlonnberg** [comment]
I've just tried upgrading a project from 8.10 to 9.40 and was able to show the view. To be able to identify the problem, I could really use the project that fails. Can you share it with me?

**Comment by fubinfeng2333** [comment]
[cube_test_tttt_0901_2.zip](https://github.com/IARSystems/iar-vsc-build/files/12545307/cube_test_tttt_0901_2.zip)
This is the project I generated with the stm32cube tool.

**Comment by jlonnberg** [comment]
The supplied project load perfectly for me and all the files are visible. Looking at your logs shows that your installation seems to have multiple compilers in the arm\bin directory. Is that the case? Does your installation for some reason contain duplicates of any other binaries?

**Comment by fubinfeng2333** [comment]
How should i check？

**Comment by fubinfeng2333** [comment]
Most of the files are different, only a few files are the same.
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/b48e7f98-90c3-43fe-93dd-c7b1b82aed8b)
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/1d2e6a80-cc72-49c1-9c8b-8967ed934d63)

**Comment by jlonnberg** [comment]
So, can you supply a list of all files matching "icc*.exe" from D:\Program Files\IAR Systems\Embedded Workbench 9.2\arm\bin

**Comment by fubinfeng2333** [comment]
![image](https://github.com/IARSystems/iar-vsc-build/assets/34903713/c9cf856e-9dda-461b-99cb-4f553c2119ef)

**Comment by jlonnberg** [comment]
It seems like your installation is corrupt, it lists multiple backup files (.bak) which should not be present. I suggest that you remove the installation and start with a fresh installation. That should fix the problem
