### ISSUE TITLE
[IAR 9.20]Could not parse workspace file...

### ISSUE THREAD

**Issue by Flymachine** [IARSystems/iar-vsc-build#56]
I got an error from IAR Build:
```
[7/25/2023, 3:49:15 PM][Error] Could not parse workspace file 'd:\demo\demo.eww': Error: Expected root tag to be 'workspace', not 'undefined'
```
The project works well with IAR 9.20.

It's the content of .eww file:
```
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- This file was generated by Simplicity Studio -->
<workspace>
  <project>
    <path>$WS_DIR$\demo.ewp</path>
  </project>
  <batchBuild/>
</workspace>
```

I found that if I delete the comment in .eww file as this:
```
<?xml version="1.0" encoding="iso-8859-1"?>
<workspace>
  <project>
    <path>$WS_DIR$\demo.ewp</path>
  </project>
  <batchBuild/>
</workspace>
```
No error reported.

That means your xml parse module has a bug.

**Comment by Flymachine** [comment]
Another question: 
I tried to set the config to exclude sdk projects:
```
"iar-build.projectsToExclude": "sdk"
```
However, I still could see the related projects in IAR Build toolbar.
For example: `d:\demo\gecko_sdk\platform\CMSIS\RTX\RTX_CM.eww`. 
They aren't ignored.

I tried to set it as:
```
"iar-build.projectsToExclude": ".*sdk.*"
```
It still didn't work.

How to set this config to ignore those projects?

**Comment by jlonnberg** [comment]
Hi,

A fix for the comment problem will be released shortly.

**Comment by jlonnberg** [comment]
Regarding the sdk projects; are you using working with an active workspace file or in folder without any .eww file?

**Comment by Flymachine** [comment]
Our project has a .eww file at the same folder as .ewp file.&nbsp; However, the SDK library we use also has some eww and ewp files. I want to find a way to ignore the root path of the SDK



---Original---
From: "Joakim ***@***.***&gt;
Date: Mon, Aug 7, 2023 15:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IARSystems/iar-vsc-build] [IAR 9.20]Could not parse workspacefile... (Issue #56)




 
Regarding the sdk projects; are you using working with an active workspace file or in folder without any .eww file?

**Comment by jlonnberg** [comment]
Regarding the filtering problem; The filter only acts on projects and not on workspaces. Moreover, the filter function is only active when working in a folder without an eww file. If an eww-file is selected, no filtering is applied and all the projects listed in the workspace will be shown in the dropdown menu for available projects.

**Comment by Flymachine** [comment]
I see.&nbsp; I misunderstood. Thanks. This issue could be closed now.&nbsp;



---Original---
From: "Joakim ***@***.***&gt;
Date: Wed, Aug 9, 2023 09:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IARSystems/iar-vsc-build] [IAR 9.20]Could not parse workspacefile... (Issue #56)




 
Regarding the filtering problem; The filter only acts on projects and not on workspaces. Moreover, the filter function is only active when working in a folder without an eww file. If an eww-file is selected, no filtering is applied and all the projects listed in the workspace will be shown in the dropdown menu for available projects.
