### ISSUE TITLE
Prevent file tree being expanded on open

### ISSUE THREAD

**Issue by allanwglen** [IARSystems/iar-vsc-build#60]
Is there any way to prevent the file tree in the IAR extension (not explorer) from expanding every time the project is opened? Explorer has an option in VSC settings to allow Expand or Collapse when the workspace is opened, but it appears this extension does expand by default.

**Comment by HampusAdolfsson** [comment]
We don't have such an option at the moment, but we can definitely add one. What is the option you are referring to for the Explorer?

Note also that there is a "Collapse All" button at the top of the file tree that might be useful to you, but I can see it being tedious to have to press it every time you load a project.

**Comment by HampusAdolfsson** [comment]
I agree! We've added an option called "Auto expand file tree", which defaults to on. It will be included in the next release.

**Comment by HampusAdolfsson** [comment]
This was closed mistakenly because we merged to master to update some documentation.
It has not been released yet, I will close it again when it has.

**Comment by micaelbo** [comment]
Next version will solve this is and it is planned for December (worst case, possibly earlier).

**Comment by HampusAdolfsson** [comment]
This just landed in 1.30.4.
