### ISSUE TITLE
Intellisense fails for NAN and INFINITY from iar math.h for RX

### ISSUE THREAD

**Issue by larlin** [IARSystems/iar-vsc-build#68]
Intellisense reports error for NAN and INFINITY macro defined in iar math.h for RX.

**To Reproduce:**
```
#include <math.h>
float test = NAN;
```

**Expected behavior:**
No error reported.

**Actual behavior:**
![image](https://github.com/IARSystems/iar-vsc-build/assets/1294907/4e2d7bbc-a1ee-471b-ab69-974399cb63f5)

**Environment:**
- OS: Windows
- Embedded Workbench:  RX
- Embedded Workbench version: 5.10.1
- VSC Extension version: v1.30.5

**Comment by HampusAdolfsson** [comment]
Hi,

The `0.NaN` literal used by the `math.h` header is an IAR C extension, and isn't understood by the C/C++ parser used in VS Code. However, you can try enabling more portable definitions with the `__RXABI_PORTABILITY_LEVEL` preprocessor define. In the extension settings, go to "Defines" and add this entry:
```
__RXABI_PORTABILITY_LEVEL=1
````
This will define it for VS Code's parser only, so it does not affect your build in any way.

**Comment by larlin** [comment]
Great that worked thanks.
