### ISSUE TITLE
Task `iar: Open Workspace in IAR Embedded Workbench` is running until the workbench is closed

### ISSUE THREAD

**Issue by pawelszramowski** [iarsystems/iar-vsc-build#80]
**Describe the bug:**
When the `iar: Open Workspace in IAR Embedded Workbench` task is used, it opens the workbench and keeps running as long as IAR is kept open. 

**To Reproduce:**
Press Ctrl + P, enter `task iar`, open the `iar` group, and choose `iar: Open Workspace in IAR Embedded Workbench`.

**Expected behavior:**
IAR EWB is started and the task finishes successfully immediately.

**Actual behavior:**
IAR EWB is started and the task only finishes successfully when IAR is closed.

**Environment:**

- OS: Windows
- Embedded Workbench: Arm
- Embedded Workbench version: 8.40
- VSC Extension version: v1.30.6

**Additional context:**
Since in some contexts it may actually be reasonable to wait until IAR is closed, it would be nice to have the waiting as a configurable option.

**Comment by HampusAdolfsson** [comment]
Thanks for the bug report!

You are right, the default behaviour should be for the task to finish immediately. I've filed a bug report internally, but I can't promise any timeline on when we'll get to it.
